services:
  storage-db:
      container_name: storagedb-container
      image: postgres
      environment:
        POSTGRES_DB: storagedb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
  billing-db:
      container_name: billing-container
      image: postgres
      environment:
        POSTGRES_DB: billingdb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5433:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
  message-broker:
      container_name: message-broker
      image: rabbitmq:3-management-alpine
      ports:
        - 5672:5672   # for sender and consumer connections
        - 15672:15672 # for serve RabbitMQ GUI
      restart: always
